#!/bin/sh

#compile dependencies:
#qt

#latex export dependencies:
#inkscape

#pdf exporting dependencies:
#rubber
#texlive-latex-recommended
#texlive-lang-polish
#texlive-latex-extra
#texlive-fonts-extra
#inkscape

make clean
qmake zsw.pro
#adjust -j# so that # = cpu cores + 1
make -j5
