#include "ResultWindow.h"
#include "ui_ResultWindow.h"
#include "Job.h"
#include "Result.h"
#include "Jobshop.h"
#include <QDebug>
#include <QtWidgets>
#include <QFileDialog>
#include <QtSvg/QSvgGenerator>
#include <QtAlgorithms>
#include <QList>
#include <QFile>
#include <QTextStream>
#include <QProcess>
#include <QTextCodec>
#include <QtDebug>
#include "ResultsModel.h"

int run(const QString &program, const QStringList &args)
{
    int rc;
    qDebug() << "running command: " << program << " args: " << args;
    rc = QProcess::execute(program, args);
    qDebug() << program << " returned code: " << rc;
    return rc;
}

void save(const QString &fileName, const QString &content)
{
    QFile file(fileName);
    file.open(QIODevice::WriteOnly | QIODevice::Text);
    QTextStream ts(&file);
    ts.setCodec(QTextCodec::codecForName("UTF-8"));
    ts << content;
    file.close();
}

ResultWindow::ResultWindow(const Chromosome& chromosome, QWidget *parent) :
    QDialog(parent),
    ui(new Ui::ResultWindow),
    m_chromosome(chromosome)
{
    ui->setupUi(this);

    setWindowModality(Qt::ApplicationModal);

    //Podsumowanie obliczeń
    //Eksport LaTeXu

    //per job stats
    ui->tableView->setModel(new ResultsModel(chromosome.results(), this));
    //global stats
    ui->label->setTextFormat(Qt::RichText);
    ui->label->setStyleSheet("QLabel { vertical-align: middle; font-size: 12pt; background-color: white; color: black; }");
    ui->label->setText(QString(
                           "Completion Time = %1<br />\n"
                           "Mean Flow Time = %2<br />\n"
                           "Number of tardy jodbs = %3 <br />\n"
                           "Maximum tardiness = %4<br />\n"
                           "<img src=:/w1> %5<br />\n"
                           "<img src=:/w2> %6<br />\n"
                           )
                       .arg(m_chromosome.completionTime())
                       .arg(m_chromosome.meanFlow())
                       .arg(m_chromosome.tardy())
                       .arg(m_chromosome.maxTardy())
                       .arg(m_chromosome.valueMean())
                       .arg(m_chromosome.valueAlpha())
                       );

    /*
        QGraphicsSimpleTextItem* text;
        QFont font("Arial", 12);
        qreal x;
        qreal ym = (maszyn*2*grafZadanie::dy)+grafZadanie::dy;

        for(int i=0; i<c; i+=5)
        {
            x = maszyna::X0 + grafZadanie::dx*i;
            scene->addLine(x, 0, x, ym);
            text = scene->addSimpleText(QString::number(i), font);
            text->setX(x+3);
            text->setY(ym-18);
        }
      ilnia z Cmax
        x = x0 + dx*c;
        scene->addLine(x, 0, x, ym);
        text = scene->addSimpleText(tr("Cmax = %1").arg(QString::number(c)), font);
        text->setX(x+3);
        text->setY(ym-18);

    ui->graphicsView->setScene(scene);
    ui->graphicsView->setAlignment(Qt::AlignLeft | Qt::AlignTop);
*/
    m_chart = Jobshop::instance()->ganttChart();

    m_scene = new QGraphicsScene(this);
    m_scene->addItem(m_chart);

    ui->graphicsView->setScene(m_scene);
    ui->graphicsView->setAlignment(Qt::AlignLeft | Qt::AlignTop);

    connect(ui->pushButton_latex, &QPushButton::clicked, this, &ResultWindow::latex);
}

ResultWindow::~ResultWindow()
{
    delete ui;
}

void ResultWindow::changeEvent(QEvent *e)
{
    QDialog::changeEvent(e);
    switch (e->type()) {
    case QEvent::LanguageChange:
        ui->retranslateUi(this);
        break;
    default:
        break;
    }
}

/*
void ResultWindow::pdf()
{
    QString fileName;
    fileName = QFileDialog::getSaveFileName(this, tr("Export wyników do pliku PDF"), "", tr("Plik PDF (*.pdf)"));
    if(fileName.isEmpty())return;

    this->pdf(fileName);
}

void ResultWindow::pdf(const QString &fileName)
{
    const QString texFile("output/wrapped.tex");

    this->latex("output/temp.tex");

    QString s;
    s =     "\\documentclass[11pt,a4paper]{article}\n"
            "\\usepackage{polski}\n" //[babel]
            "\\usepackage[utf8]{inputenc}\n"
            "\\usepackage{mathtools}\n"
            "\\usepackage{color}\n"
            "\\usepackage{graphicx}\n"
            "\\usepackage{lscape}\n"
            "\\usepackage{transparent}\n"
            "\\mathtoolsset{showonlyrefs}\n"
            "\\title{Generated by kSzereg}\n"
            "\\date{}\n"
            "\\begin{document}\n"
            "\t\\input{";
    s +=    "temp.tex";
    s +=    "}\n"
            "\\end{document}\n";

    save(texFile, s);

    QStringList args;
    args << "--pdf" << "--inplace" << "-I" << "output" << texFile;
    run("rubber", args);

    args.clear();
    args << "--clean" << "--inplace" << texFile;
    run("rubber", args);

    QDir::current().rename("output/wrapped.pdf", fileName);
}
*/
void ResultWindow::latex()
{
    QString fileName;
    fileName = QFileDialog::getSaveFileName(this, tr("Export wyników do LaTeXu"), "", tr("Plik tex (*.tex)"));
    if(fileName.isEmpty())return;
    this->latex2(fileName);
}

void ResultWindow::latex2(const QString &texName)
{
    /*===================
     * TODO
     *========================/
    QString s;
    Result* st;

    QFileInfo fi(texName);
    const QString name = fi.baseName();
    const QString svgName(tr("output/gantt_%1.svg").arg(name));
    const QString pdfName(tr("gantt_%1.pdf").arg(name));

    QSvgGenerator svgGen;
    svgGen.setFileName(svgName);
    svgGen.setSize(QSize(1000, 500));
    svgGen.setViewBox(QRect(0, 0, 1000, 500));
    svgGen.setTitle(tr("Gantt chart"));
    svgGen.setDescription(tr("Gantt chart"));
    QPainter painter;
    painter.begin(&svgGen);
  //  painter.rotate(rot);
    scene->render(&painter);
    painter.end();

    QStringList args;
    args << "-z" << "-f" << svgName << "--export-latex" << "--export-pdf" << tr("output/%1").arg(pdfName) << "-D";
    run("inkscape", args);

    s =     "\n%Tabela danych\n\n"
            "\t\\begin{table}[htb]\n"
            "\t\t\\centering\n"
            "\t\t\\caption{Struktura zlecenia}\n"
            "\t\t\\begin{tabular}{ | r | c | c | l | }\n"
            "\t\t\\hline\n"
            "\t\tj\t& \\(r_j\\)\t& \\(d_j\\)\t& Marszruta technologiczna\t\\\\ \\hline\n";
    Job* z;
    foreach(z, *zadania)
    {
        s += "\t\t";
        s += z->id();
        s += "\t& ";
        s += QString::number(z->arrival());
        s += "\t& ";
        s += QString::number(z->dueDate());
        s += "\t& ";
        s += z->print();
        s += "\t\\\\ \\hline\n";
    }
    s +=    "\t\t\\end{tabular}\n"
            "\t\\end{table}\n";

    s +=    "\n%Tabela wynikowa\n\n"
            "\t\\begin{table}[htb]\n"
            "\t\t\\centering\n"
            "\t\t\\caption{Parametry wykonanych zadań}\n"
            "\t\t\\begin{tabular}{ | r | c | c | c | c |}\n"
            "\t\t\\hline\n"
            "\t\tj\t& \\(c_j\\)\t& \\(f_j\\)\t& \\(l_j\\)\t& \\(e_j\\)\t\\\\ \\hline\n";

    qSort(stats.begin(), stats.end());

    foreach(st, stats)
    {
        s += "\t\t";
        s += QString::number(st->j());
        s += "\t& ";
        s += QString::number(st->cj());
        s += "\t& ";
        s += QString::number(st->fj());
        s += "\t& ";
        s += QString::number(st->lj());
        s += "\t& ";
        s += QString::number(st->ej());
        s += "\t\\\\ \\hline\n";
    }

    s +=    "\t\t\\end{tabular}\n"
            "\t\\end{table}\n";

    s +=    "\n%Tabela wyznacznikow\n\n"
            "\t\\begin{table}[htb]\n"
            "\t\t\\centering\n"
            "\t\t\\begin{tabular}{ l l l }\n"
            "\t\t\\(C_{max} = ";
    s +=    QString::number(c);
    s +=    " \\)\t& \\( T_{max} = ";
    s +=    QString::number(Tmax);
    s +=    " \\)\t& \\( \\sqrt{\\sum e_j^2 + \\sum l_j^2} = ";
    s +=    QString::number(w1);
    s +=    "\\)\t\\\\\n"
            "\t\t\\( \\bar{F} = ";
    s +=    QString::number(f);
    s +=    " \\)\t& \\( \\bar{T} = ";
    s +=    QString::number(Tsr);
    s +=    " \\)\t& \\( \\alpha*\\sum e_j + \\beta*\\sum l_j \\Big|_{\\substack{\\alpha = ";
    s +=    QString::number(alfa);
    s +=    "\\\\ \\beta = ";
    s +=    QString::number(beta);
    s +=    "}} = ";
    s +=    QString::number(w2);
    s +=    " \\)\t\\\\ \n";
    s +=    "\t\t\\end{tabular}\n"
            "\t\\end{table}\n";

    s +=    "%wykres gantt'a\n"
           "\t\\begin{figure}[htb]\n"
           "\t\t\\centering\n"
           "\t\t\\def\\svgwidth{\\columnwidth}\n"
           "\t\t\\input{";
    s +=    pdfName + "_tex}\n"
            "\t\t\\caption{Wykres Gantt'a}\n"
            "\t\\end{figure}\n"
            "\t\\FloatBarrier\n";
    save(texName, s);
    */
}
