#!/bin/sh
#cd ../
#rm output/*
#./compile
#./kSzereg -l lista -h all
#cd praca
rubber --pdf -I ../output prezentacja.tex
rubber --clean prezentacja.tex
rm prezentacja.nav prezentacja.snm prezentacja.out
#evince prezentacja.pdf

